### PR TITLE
Set a default value for con in writeLines

### LINKED ISSUE #13: brio::writeLines and base::writeLines have slightly different function signatures
Base's `writeLines()` has a default value for con:

```
writeLines(text, con = stdout(), sep = "\n", useBytes = FALSE)
```

Which can cause errors if brio is used as a drop-in.

### PR DESCRIPTION
**Pull request by michaelquinn32**
Fixes #13

### CODE REVIEW

**Comment by jimhester** [comment]
`brio::writeLines()` does not accept connections, only character strings representing paths, so this change would simply result in a `Only file paths are supported by brio::writeLines()` error message.

**Comment by michaelquinn32** [comment]
Would it be possible to support connections? We use a generic file system that is implemented using connections.
https://stackoverflow.com/a/42936700

It would be nice if brio could support that too. Otherwise, we're seeing scripts that inadvertently load this package through transitive dependencies fail because of changes to a base function's behavior.

**Comment by michaelquinn32** [comment]
A patch that I'm implementing right now makes writeLines and readLines generics. For connections, we could use base, but otherwise could rely on brio. Does that work for you too?

**Comment by gaborcsardi** [comment]
Fwiw, if you have an already opened connection then there is no way to ensure that the input or output will be UTF-8.

**Comment by jimhester** [comment]
@michaelquinn32, sure, I guess that is the best we can do, though I wonder if we should issue a warning in this case.

**Comment by michaelquinn32** [comment]
Thanks for all of the feedback. Let me know what you think!

**Comment by gaborcsardi** [comment]
I am sorry for the extreme long wait on this. Since there is no way to change the encoding of an already opened connection, AFAICT there is no way to ensure that the result will be UTF-8. So I am going to close this.

**Pull request closed without merging**
